name = "Poly"
license = "MIT"
licenselink = "https://github.com/minizatic/poly/LICENSE.md"
description = "Minimal blog theme for Hugo"
homepage = "http://blog.blakepatches.me/"
tags = ["", ""]
features = ["", ""]

[author]
  name = "Blake Patches"
  homepage = "http://blakepatches.me"
